module.exports = {
  "url": "https://master.ds6e6jixc9bcf.amplifyapp.com/",
  "ozInput": "div:nth-of-type(1) > .box-item > input",
  "mlFormValue": "div:nth-of-type(1) > .box-item > h1:nth-of-type(2)",
  "lbInput": "div:nth-of-type(2) > .box-item > input",
  "kgFormValue": "div:nth-of-type(2) > .box-item > h1:nth-of-type(2)",
  "tablespoonInput": "div:nth-of-type(3) > .box-item > input",
  "teaspoonInput": "div:nth-of-type(3) > .box-item > h1:nth-of-type(2)",
  "celiciousInput": "div:nth-of-type(4) > .box-item > input",
  "fahrenheitFormValue": "div:nth-of-type(4) > .box-item > h1:nth-of-type(2)",
  "StopWatchTime": "#stop-watch-time",
  "StopWatchStartButton": "#start-button",
  "StopWatchStopButton": "#stop-button",
  "StopWatchResetButton": "#reset-button",
}